import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Sparkles, Zap, Rocket, ArrowRight, Lock, Shield } from "lucide-react";
import { toast } from "sonner";

export default function Builder() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null);
  const [userTier, setUserTier] = useState("free");
  const [loading, setLoading] = useState(true);
  const [formData, setFormData] = useState({
    brand_name: "",
    industry: "",
    description: ""
  });
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    checkAuth();
  }, []);

  const checkAuth = async () => {
    try {
      const isAuthenticated = await base44.auth.isAuthenticated();
      
      if (!isAuthenticated) {
        toast.error("🔒 Please log in to use NeuroScopes AI Builder");
        base44.auth.redirectToLogin(createPageUrl("Builder"));
        return;
      }

      const currentUser = await base44.auth.me();
      setUser(currentUser);

      // Check subscription status
      const subscriptions = await base44.entities.Subscription.filter({
        user_email: currentUser.email,
        status: "active"
      });

      if (subscriptions.length > 0) {
        const sub = subscriptions[0];
        // Check if monthly subscription is expired
        if (sub.tier === "monthly" && sub.expires_at) {
          const expireDate = new Date(sub.expires_at);
          if (expireDate < new Date()) {
            await base44.entities.Subscription.update(sub.id, { status: "expired" });
            setUserTier("free");
          } else {
            setUserTier(sub.tier);
          }
        } else {
          setUserTier(sub.tier);
        }
      }
    } catch (error) {
      console.error("Auth check failed:", error);
      toast.error("Authentication failed. Please log in.");
      base44.auth.redirectToLogin(createPageUrl("Builder"));
    }
    setLoading(false);
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    setIsGenerating(true);

    try {
      // Verify authentication
      if (!user) {
        toast.error("🔒 Authentication required");
        base44.auth.redirectToLogin(createPageUrl("Builder"));
        return;
      }

      // NeuroScopes AI Generation Prompt (Firewalled)
      const systemPrompt = `You are NeuroScopes AI, a premium website builder that generates production-ready websites.
User Tier: ${userTier}
Security: Verified user token from Base44 authentication system.

Generate a complete website structure following this exact JSON schema:

{
  "public_preview": {
    "headline": "string (max 10 words, compelling)",
    "subheadline": "string (1 sentence value proposition)",
    "preview_points": ["string", "string", "string"],
    "cta": "Unlock Full Build",
    "preview_notice": "Free sample generated by NeuroScopes AI"
  },
  "premium_content": {
    "title": "string (SEO title)",
    "meta_description": "string (150-160 chars)",
    "hero_section": {
      "headline": "string",
      "subheadline": "string",
      "cta_text": "string"
    },
    "about_section": {
      "headline": "string",
      "paragraph_1": "string",
      "paragraph_2": "string"
    },
    "solutions": [
      {"title": "string", "description": "string", "icon_suggestion": "string"},
      {"title": "string", "description": "string", "icon_suggestion": "string"},
      {"title": "string", "description": "string", "icon_suggestion": "string"}
    ],
    "testimonials": [
      {"quote": "string", "author": "string", "role": "string"},
      {"quote": "string", "author": "string", "role": "string"},
      {"quote": "string", "author": "string", "role": "string"}
    ],
    "pricing": {
      "plans": [
        {"name": "Starter", "price": "$199/mo", "features": ["string", "string", "string"]},
        {"name": "Growth", "price": "$499/mo", "features": ["string", "string", "string", "string"]},
        {"name": "Enterprise", "price": "Custom", "features": ["string", "string", "string", "string", "string"]}
      ]
    },
    "contact": {
      "email": "hello@${formData.brand_name.toLowerCase().replace(/\s+/g, '')}.com",
      "phone": "+1 (555) 000-0000",
      "address": "Remote / Global"
    },
    "full_html": "string (complete HTML page with inline CSS using dark theme, neural gradients)"
  },
  "paywall": "active",
  "pricing_tiers": {
    "free": "Public preview only",
    "pro_monthly": "$9/mo",
    "pro_one_time": "$29 one-time"
  }
}

Brand: ${formData.brand_name}
Industry: ${formData.industry}
Description: ${formData.description}

Requirements:
- Professional, conversion-optimized copy
- Dark neural aesthetic (deep navy, electric blue, violet)
- Credible tone - no hype, evidence-based
- SEO optimized
- Production-ready HTML with modern CSS`;

      const result = await base44.integrations.Core.InvokeLLM({
        prompt: systemPrompt,
        response_json_schema: {
          type: "object",
          properties: {
            public_preview: {
              type: "object",
              properties: {
                headline: { type: "string" },
                subheadline: { type: "string" },
                preview_points: { type: "array", items: { type: "string" } },
                cta: { type: "string" },
                preview_notice: { type: "string" }
              }
            },
            premium_content: {
              type: "object",
              properties: {
                title: { type: "string" },
                meta_description: { type: "string" },
                hero_section: { type: "object" },
                about_section: { type: "object" },
                solutions: { type: "array" },
                testimonials: { type: "array" },
                pricing: { type: "object" },
                contact: { type: "object" },
                full_html: { type: "string" }
              }
            },
            paywall: { type: "string" },
            pricing_tiers: { type: "object" }
          }
        }
      });

      // Security check - verify response structure
      if (!result.public_preview || !result.premium_content) {
        throw new Error("Invalid response structure from AI");
      }

      // Save to database
 
